# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VlJBZ2WlU0fyKzwV4rkcZE2dvoUNCTkP
"""



a=float(input("a:"))
b=float(input("b:"))
c=float(input("c:"))
total=a+b+c
if(total>50):
  result=total-(total*10)/100
  print("Total Cost:",result)
else:
  print("Total Cost:",total)